// <auto-generated />
using System;
using ImageDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _401_abdullin.Migrations
{
    [DbContext(typeof(DatabaseStoreContext))]
    partial class DatabaseStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ImageDatabase.ProcessedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bitmap")
                        .HasColumnType("BLOB");

                    b.Property<int>("Hash")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProcessedImages");
                });

            modelBuilder.Entity("ImageDatabase.RecognizedObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedImageId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("X1")
                        .HasColumnType("REAL");

                    b.Property<float>("X2")
                        .HasColumnType("REAL");

                    b.Property<float>("Y1")
                        .HasColumnType("REAL");

                    b.Property<float>("Y2")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedImageId");

                    b.ToTable("RecognizedObjects");
                });

            modelBuilder.Entity("ImageDatabase.RecognizedObject", b =>
                {
                    b.HasOne("ImageDatabase.ProcessedImage", null)
                        .WithMany("RecognizedObjects")
                        .HasForeignKey("ProcessedImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImageDatabase.ProcessedImage", b =>
                {
                    b.Navigation("RecognizedObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
